version: '3'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
#    ports:
#      - 5435:5432
  web:
    build: .
    command: python /home/owerpy/python/cook_blog-main/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/owerpy/python/cook_blog-main/
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data: